links:
  - platform: "Facebook"
    url: "https://facebook.com/tertnesbr"
  - platform: "Instagram"
    url: "https://instagram.com/tertnesbrass"
  - platform: "Twitter"
    url: "https://x.com/TertnesBrass"
  - platform: "YouTube"
    url: "https://youtube.com/@tertnesbrass"
  - platform: "SoundCloud"
    url: "https://soundcloud.com/tertnesbrass"
  - platform: "Spotify"
    url: "https://open.spotify.com/artist/4Zjbwup3aOmL8erBFGLT7C"
